services:
  next:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "file:./prisma/dev.db"
      NEXT_PUBLIC_APP_NETWORK_ID: "testnet"
      NODE_ENV: "development"
    volumes:
      - .:/app
      - /app/node_modules
